/** Homeowner dashboard + task card surface styles (shared). */
const homeownerDashboardStyles ={
    dashboardShell: {
        width: '100%',
        minHeight: 'calc(100vh - 70px)',
        backgroundColor: '#F9FAFB',
        backgroundImage: 'none',
        position: 'relative',
        zIndex: 0,
        overflow: 'hidden',
        isolation: 'isolate',
    },
    dashboardContainer: {
        fontFamily: 'Inter, sans-serif',
        padding: '32px 24px',
        maxWidth: '960px',
        margin: '0 auto',
        position: 'relative',
        zIndex: 0,
        backgroundColor: 'transparent',
        backgroundImage: 'none',
    },

    welcomeSection: {
        marginBottom: '28px',
    },
    greeting: {
        fontFamily: 'Poppins, sans-serif',
        fontSize: '24px',
        fontWeight: '600',
        color: '#111827',
        marginBottom: '4px',
    },
    helperLine: {
        fontSize: '13px',
        color: '#6B7280',
        fontWeight: '400',
        marginBottom: '4px',
        lineHeight: 1.45,
    },
    subGreeting: {
        fontSize: '15px',
        color: '#6B7280',
        fontWeight: '400',
    },

    emptyState: {
        textAlign: 'center',
        padding: '80px 40px',
        backgroundColor: '#FFFFFF',
        borderRadius: '16px',
        border: '1px solid #E5E7EB',
        maxWidth: '600px',
        margin: '0 auto',
        boxShadow: '0 2px 12px rgba(15, 23, 42, 0.04)',
    },
    emptyIcon: {
        marginBottom: '24px',
    },
    emptyTitle: {
        fontFamily: 'Poppins, sans-serif',
        fontSize: '24px',
        fontWeight: '600',
        color: '#111827',
        marginBottom: '12px',
    },
    emptyText: {
        fontSize: '16px',
        color: '#4B5563',
        lineHeight: '1.6',
        marginBottom: '32px',
    },
    ctaButtonBase: {
        fontFamily: 'Inter, sans-serif',
        borderRadius: '10px',
        fontSize: '14px',
        fontWeight: '600',
        cursor: 'pointer',
        border: 'none',
        lineHeight: 1.3,
    },
    ctaPost: {
        backgroundColor: '#14C5C5',
        color: '#FFFFFF',
        boxShadow: '0 2px 8px rgba(20, 197, 197, 0.25)',
    },

    sectionBlock: {
        marginBottom: '28px',
    },
    sectionDefaultShell: {
        padding: 0,
    },
    sectionNeedsActionShell: {
        backgroundColor: '#FFF7ED',
        borderRadius: '14px',
        padding: '20px',
        border: 'none',
        boxShadow: 'none',
    },
    sectionHeader: {
        marginBottom: '16px',
    },
    sectionEyebrow: {
        fontSize: '11px',
        fontWeight: '700',
        letterSpacing: '0.1em',
        textTransform: 'uppercase',
        color: '#C2410C',
        marginBottom: '6px',
    },
    sectionHeading: {
        fontFamily: 'Poppins, sans-serif',
        fontSize: '18px',
        fontWeight: '700',
        color: '#111827',
        margin: '0 0 6px 0',
        lineHeight: 1.45,
    },
    sectionHeadingMuted: {
        fontFamily: 'Poppins, sans-serif',
        fontSize: '18px',
        fontWeight: '700',
        color: '#64748B',
        opacity: 0.92,
        margin: '0 0 6px 0',
        lineHeight: 1.45,
    },
    sectionHeadingPriority: {
        fontFamily: 'Poppins, sans-serif',
        fontSize: '20px',
        fontWeight: '700',
        color: '#111827',
        margin: '0 0 8px 0',
        lineHeight: 1.45,
    },
    sectionSub: {
        fontSize: '14px',
        color: '#6B7280',
        margin: 0,
        lineHeight: 1.5,
    },
    sectionEmpty: {
        paddingTop: '4px',
        paddingBottom: '2px',
    },
    sectionEmptyText: {
        fontSize: '14px',
        color: '#6B7280',
        margin: '0 0 10px 0',
        lineHeight: 1.5,
    },
    sectionEmptyCtaBtn: {
        backgroundColor: '#FFFFFF',
        color: '#0F766E',
        border: '1px solid #A5F3FC',
        padding: '8px 14px',
        fontSize: '13px',
        fontWeight: '600',
    },

    jobList: {
        display: 'grid',
        gap: '16px',
        gridTemplateColumns: '1fr',
    },

    jobCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: '14px',
        padding: '19px 24px 17px',
        display: 'flex',
        flexDirection: 'column',
        cursor: 'pointer',
        outline: 'none',
    },
    cardHeaderRow: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        gap: '14px',
        marginBottom: '10px',
    },
    titleCluster: {
        display: 'flex',
        alignItems: 'flex-start',
        gap: '8px',
        flex: 1,
        minWidth: 0,
    },
    jobTitle: {
        fontFamily: 'Poppins, sans-serif',
        fontSize: '18px',
        fontWeight: '700',
        color: '#111827',
        margin: 0,
        lineHeight: 1.45,
        flex: 1,
        minWidth: 0,
    },
    unreadBadge: {
        flexShrink: 0,
        minWidth: '20px',
        height: '20px',
        padding: '0 6px',
        borderRadius: '999px',
        backgroundColor: '#F3F4F6',
        color: '#6B7280',
        fontSize: '11px',
        fontWeight: '700',
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        lineHeight: 1,
        marginTop: '2px',
    },
    cardHeaderRight: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'flex-end',
        gap: '6px',
        flexShrink: 0,
        maxWidth: '180px',
    },
    trustPillsRow: {
        display: 'flex',
        flexDirection: 'row',
        flexWrap: 'nowrap',
        gap: '4px',
        justifyContent: 'flex-end',
        maxWidth: '160px',
    },
    trustPill: {
        fontSize: '11px',
        fontWeight: '600',
        lineHeight: 1.25,
        padding: '3px 8px',
        borderRadius: '999px',
        whiteSpace: 'nowrap',
        maxWidth: '160px',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        boxSizing: 'border-box',
    },
    trustPillSecure: {
        backgroundColor: '#ECFDF5',
        color: '#047857',
    },
    statusBadge: {
        display: 'inline-block',
        padding: '5px 9px',
        borderRadius: '999px',
        fontSize: '11px',
        fontWeight: '600',
        lineHeight: 1.25,
        maxWidth: '140px',
        textAlign: 'left',
        boxSizing: 'border-box',
        flexShrink: 0,
        whiteSpace: 'nowrap',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
    },
    jobMeta: {
        fontSize: '13px',
        color: '#64748B',
        lineHeight: 1.45,
        marginBottom: '8px',
        fontWeight: '500',
    },
    cardGuidanceBlock: {
        marginBottom: '6px',
    },
    cardGuidancePrimary: {
        fontSize: '13px',
        fontWeight: '400',
        color: '#94A3B8',
        lineHeight: 1.45,
        marginBottom: '4px',
    },
    cardGuidanceHelper: {
        fontSize: '12px',
        fontWeight: '400',
        color: '#9CA3AF',
        lineHeight: 1.45,
        marginBottom: '3px',
    },
    expertTrustBlock: {
        marginBottom: '6px',
    },
    expertTrustName: {
        fontSize: '13px',
        fontWeight: '500',
        color: '#4B5563',
        lineHeight: 1.45,
        marginBottom: '4px',
    },
    expertTrustRatingRow: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: '6px',
        fontSize: '13px',
        color: '#374151',
        lineHeight: 1.45,
        marginBottom: '2px',
        maxWidth: '100%',
    },
    expertTrustStarIcon: {
        flexShrink: 0,
    },
    expertTrustRatedBadge: {
        fontSize: '11px',
        fontWeight: '600',
        padding: '2px 7px',
        borderRadius: '999px',
        backgroundColor: '#FFFBEB',
        color: '#B45309',
        border: '1px solid #FDE68A',
        whiteSpace: 'nowrap',
        maxWidth: '120px',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
    },
    expertTrustJobsLine: {
        fontSize: '12px',
        color: '#94A3B8',
        lineHeight: 1.45,
    },
    expertTrustNewExpert: {
        fontSize: '12px',
        color: '#6B7280',
        lineHeight: 1.45,
        fontWeight: '400',
    },
    expertTrustResponse: {
        fontSize: '13px',
        color: '#374151',
        lineHeight: 1.45,
        marginBottom: '6px',
    },
    progressLine: {
        fontSize: '13px',
        fontWeight: '500',
        color: '#475569',
        lineHeight: 1.45,
        marginBottom: '2px',
    },
    paymentEscrowHint: {
        fontSize: '12px',
        fontWeight: '400',
        color: '#94A3B8',
        lineHeight: 1.45,
        marginTop: '4px',
        marginBottom: '2px',
    },
    optionalContextLine: {
        fontSize: '13px',
        fontWeight: '400',
        color: '#64748B',
        lineHeight: 1.45,
        marginTop: '4px',
    },
    optionalContextHint: {
        fontSize: '12px',
        fontWeight: '400',
        color: '#94A3B8',
        lineHeight: 1.4,
        marginTop: '2px',
    },
    staleHint: {
        fontSize: '12px',
        fontWeight: '400',
        color: '#C2410C',
        lineHeight: 1.4,
        marginTop: '4px',
        opacity: 0.92,
    },
    cardDivider: {
        height: '1px',
        backgroundColor: '#EEF2F6',
        margin: '10px 0 0',
        width: '100%',
    },

    ctaHelperText: {
        fontSize: '12px',
        color: '#6B7280',
        margin: '6px 0 0 0',
        lineHeight: 1.45,
        fontWeight: '400',
    },
    ctaContextHint: {
        fontSize: '12px',
        color: '#6B7280',
        margin: '6px 0 0 0',
        lineHeight: 1.45,
        fontWeight: '400',
    },
    taskRefLine: {
        fontSize: '12px',
        color: '#94A3B8',
        margin: '8px 0 0 0',
        lineHeight: 1.35,
        fontWeight: '400',
        opacity: 0.5,
    },

    ctaPrimaryPayment: {
        backgroundColor: '#EA580C',
        color: '#FFFFFF',
        border: '1px solid #EA580C',
        padding: '10px 18px',
        boxShadow: 'none',
        fontWeight: '600',
        width: '100%',
        marginTop: '13px',
        boxSizing: 'border-box',
    },
    ctaPrimaryApprove: {
        backgroundColor: '#14C5C5',
        color: '#FFFFFF',
        border: '1px solid #14C5C5',
        padding: '10px 18px',
        boxShadow: 'none',
        fontWeight: '600',
        width: '100%',
        marginTop: '13px',
        boxSizing: 'border-box',
    },
    ctaSecondary: {
        backgroundColor: '#FFFFFF',
        color: '#0F766E',
        border: '1px solid #A5F3FC',
        padding: '10px 18px',
        boxShadow: 'none',
        fontWeight: '600',
        width: '100%',
        marginTop: '13px',
        boxSizing: 'border-box',
    },
    ctaPassive: {
        backgroundColor: '#F9FAFB',
        color: '#4B5563',
        border: '1px solid #E5E7EB',
        padding: '10px 18px',
        boxShadow: 'none',
        fontWeight: '600',
        width: '100%',
        marginTop: '13px',
        boxSizing: 'border-box',
    },

export default homeownerDashboardStyles;
