/**
 * Shared styles for the admin Dashboard.
 * Extracted to reduce maintainability debt in Dashboard.js.
 */
export const dashboardStyles = {
  container: { padding: 32, maxWidth: 1400, margin: '0 auto', minHeight: 'calc(100vh - 64px)', backgroundColor: '#F7F9FA' },
  welcomeSection: { marginBottom: 32 },
  greeting: { fontFamily: 'Poppins, sans-serif', fontSize: 24, fontWeight: 600, color: '#222', marginBottom: 4 },
  subGreeting: { fontSize: 14, color: '#757575', fontWeight: 400 },
  centered: { padding: 40, textAlign: 'center' },

  attentionStrip: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
    gap: 12,
    marginBottom: 18,
  },
  attentionCard: {
    textAlign: 'left',
    padding: 14,
    borderRadius: 12,
    border: '1px solid #E5E7EB',
    backgroundColor: '#FFFFFF',
    cursor: 'pointer',
    boxShadow: '0 1px 2px rgba(0,0,0,0.04)',
  },
  attentionValue: { fontSize: 22, fontWeight: 900, color: '#111827', marginBottom: 4, fontFamily: 'Poppins, sans-serif' },
  attentionLabel: { fontSize: 12.5, color: '#6B7280', fontWeight: 700, lineHeight: 1.25 },

  betaPill: {
    display: 'inline-block',
    marginLeft: 8,
    fontSize: 11,
    fontWeight: 900,
    padding: '2px 8px',
    borderRadius: 999,
    border: '1px solid #E5E7EB',
    backgroundColor: '#F9FAFB',
    color: '#6B7280',
    verticalAlign: 'middle',
  },
  betaTiny: { fontSize: 11, fontWeight: 900, color: '#6B7280' },
  boostBtn: { padding: '8px 16px', cursor: 'pointer', backgroundColor: '#fff', color: '#374151', border: '1px solid #d1d5db', borderRadius: 6, fontWeight: 800, fontSize: 14 },
  boostBtnActive: { padding: '8px 16px', cursor: 'pointer', backgroundColor: '#111827', color: '#fff', border: '1px solid #111827', borderRadius: 6, fontWeight: 900, fontSize: 14 },

  statsContainer: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: 16,
    marginBottom: 24,
  },
  statCard: {
    border: '1px solid #ddd',
    borderRadius: 8,
    padding: 20,
    textAlign: 'center',
    backgroundColor: '#f9fafb',
  },
  statValue: { fontSize: 32, fontWeight: 700, color: '#1f2937', marginBottom: 4 },
  statLabel: { fontSize: 14, fontWeight: 600, color: '#6b7280', marginBottom: 4 },
  statSubtext: { fontSize: 12, color: '#9ca3af' },

  tabContainer: {
    display: 'flex',
    gap: 8,
    marginBottom: 16,
    borderBottom: '2px solid #e5e7eb',
  },
  tab: {
    padding: '12px 24px',
    border: 'none',
    background: 'transparent',
    cursor: 'pointer',
    fontWeight: 500,
    color: '#6b7280',
    borderBottom: '2px solid transparent',
    marginBottom: -2,
  },
  tabActive: {
    padding: '12px 24px',
    border: 'none',
    background: 'transparent',
    cursor: 'pointer',
    fontWeight: 600,
    color: '#2563eb',
    borderBottom: '2px solid #2563eb',
    marginBottom: -2,
  },

  card: {
    border: '1px solid #ddd',
    borderRadius: 8,
    padding: 16,
    marginBottom: 16,
    backgroundColor: '#fff',
  },
  cardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    flexWrap: 'wrap',
    marginBottom: 16,
    paddingBottom: 12,
    borderBottom: '1px solid #e5e7eb',
  },
  sectionTitle: { margin: 0 },

  scrollableList: {
    maxHeight: '600px',
    overflowY: 'auto',
    border: '1px solid #e5e7eb',
    borderRadius: 6,
  },

  button: {
    padding: '8px 16px',
    cursor: 'pointer',
    backgroundColor: '#2563eb',
    color: '#fff',
    border: 'none',
    borderRadius: 6,
    fontWeight: 500,
    fontSize: 14,
  },
  buttonSecondary: {
    padding: '8px 16px',
    cursor: 'pointer',
    backgroundColor: '#f3f4f6',
    color: '#374151',
    border: '1px solid #d1d5db',
    borderRadius: 6,
    fontWeight: 500,
    fontSize: 14,
  },

  filterPillsContainer: {
    display: 'flex',
    gap: 8,
    padding: '12px 16px',
    borderBottom: '1px solid #e5e7eb',
    flexWrap: 'wrap',
    backgroundColor: '#f9fafb',
  },
  quickFiltersRow: {
    display: 'flex',
    gap: 8,
    padding: '10px 16px',
    borderBottom: '1px solid #e5e7eb',
    flexWrap: 'wrap',
    backgroundColor: '#fff',
    alignItems: 'center',
  },
  quickFilter: {
    height: 34,
    padding: '0 12px',
    borderRadius: 999,
    border: '1px solid #d1d5db',
    background: '#fff',
    color: '#374151',
    fontWeight: 800,
    cursor: 'pointer',
    fontSize: 13,
  },
  quickFilterActive: {
    height: 34,
    padding: '0 12px',
    borderRadius: 999,
    border: '1px solid #111827',
    background: '#111827',
    color: '#fff',
    fontWeight: 900,
    cursor: 'pointer',
    fontSize: 13,
  },
  quickFilterClear: {
    height: 34,
    padding: '0 12px',
    borderRadius: 10,
    border: '1px solid #d1d5db',
    background: '#fff',
    color: '#374151',
    fontWeight: 900,
    cursor: 'pointer',
    fontSize: 13,
    marginLeft: 'auto',
  },
  filterPill: {
    padding: '6px 14px',
    cursor: 'pointer',
    backgroundColor: '#fff',
    color: '#6b7280',
    border: '1px solid #d1d5db',
    borderRadius: 20,
    fontWeight: 500,
    fontSize: 13,
    transition: 'all 0.2s',
    whiteSpace: 'nowrap',
  },
  filterPillActive: {
    padding: '6px 14px',
    cursor: 'pointer',
    backgroundColor: '#2563eb',
    color: '#fff',
    border: '1px solid #2563eb',
    borderRadius: 20,
    fontWeight: 600,
    fontSize: 13,
    boxShadow: '0 2px 4px rgba(37, 99, 235, 0.2)',
    whiteSpace: 'nowrap',
  },

  healthBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    padding: '4px 10px',
    borderRadius: 999,
    fontWeight: 900,
    fontSize: 12,
    border: '1px solid #E5E7EB',
    background: '#F9FAFB',
    color: '#374151',
  },
  healthDanger: { background: '#fff1f2', borderColor: '#fecdd3', color: '#9f1239' },
  healthWarning: { background: '#fff7ed', borderColor: '#fed7aa', color: '#9a3412' },
  healthInfo: { background: '#eff6ff', borderColor: '#bfdbfe', color: '#1d4ed8' },
  healthSuccess: { background: '#ecfdf5', borderColor: '#a7f3d0', color: '#065f46' },

  rowActions: { display: 'flex', gap: 8, alignItems: 'center', marginLeft: 12, flexWrap: 'wrap', justifyContent: 'flex-end' },
  rowActionBtn: {
    padding: '8px 12px',
    borderRadius: 10,
    textDecoration: 'none',
    fontWeight: 900,
    backgroundColor: '#14C5C5',
    color: '#fff',
    border: '1px solid #0EA5A5',
    fontSize: 13,
    whiteSpace: 'nowrap',
  },
  rowActionBtnSecondary: {
    padding: '8px 12px',
    borderRadius: 10,
    textDecoration: 'none',
    fontWeight: 900,
    backgroundColor: '#fff',
    color: '#374151',
    border: '1px solid #d1d5db',
    fontSize: 13,
    whiteSpace: 'nowrap',
    cursor: 'pointer',
  },

  modalOverlay: { position: 'fixed', inset: 0, backgroundColor: 'rgba(0,0,0,0.45)', display: 'flex', justifyContent: 'center', alignItems: 'center', padding: 16, zIndex: 1000 },
  modalCard: { width: '100%', maxWidth: 560, backgroundColor: '#fff', borderRadius: 12, padding: 16, boxShadow: '0 10px 30px rgba(0,0,0,0.18)', boxSizing: 'border-box' },
  modalTextarea: { width: '100%', maxWidth: '100%', boxSizing: 'border-box', borderRadius: 10, border: '1px solid #E0E0E0', padding: 10, fontFamily: 'Inter, sans-serif', fontSize: 14, resize: 'vertical', display: 'block' },
  inlineLinkBtn: { border: 'none', background: 'transparent', padding: 0, color: '#14C5C5', fontWeight: 900, cursor: 'pointer', fontSize: 12, textDecoration: 'underline' },

  drawerOverlay: { position: 'fixed', inset: 0, backgroundColor: 'rgba(0,0,0,0.45)', zIndex: 1200, display: 'flex', justifyContent: 'flex-end' },
  drawerPanel: { width: '100%', maxWidth: 420, height: '100%', backgroundColor: '#fff', boxShadow: '0 10px 30px rgba(0,0,0,0.20)', display: 'flex', flexDirection: 'column' },
  drawerHeader: { padding: 14, borderBottom: '1px solid #E5E7EB', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 10 },
  drawerTitle: { fontFamily: 'Poppins, sans-serif', fontSize: 16, fontWeight: 900, color: '#111827' },
  drawerSubtitle: { marginTop: 4, fontSize: 12, color: '#6B7280', fontWeight: 800, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  drawerCloseBtn: { height: 34, width: 34, borderRadius: 10, border: '1px solid #E5E7EB', background: '#fff', cursor: 'pointer', fontWeight: 900, color: '#111827' },
  drawerSection: { marginBottom: 14 },
  drawerSectionTitle: { fontSize: 12, fontWeight: 900, color: '#374151', marginBottom: 8, textTransform: 'uppercase', letterSpacing: 0.6 },
  drawerGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 },
  drawerItem: { border: '1px solid #E5E7EB', borderRadius: 12, padding: 10, background: '#F9FAFB' },
  drawerKey: { display: 'block', fontSize: 11, fontWeight: 900, color: '#6B7280', marginBottom: 4 },
  drawerVal: { display: 'block', fontSize: 13, fontWeight: 900, color: '#111827' },
  drawerFooter: { marginTop: 10, display: 'grid', gridTemplateColumns: '1fr', gap: 10 },
  drawerTextarea: { width: '100%', boxSizing: 'border-box', borderRadius: 10, border: '1px solid #E0E0E0', padding: 10, fontFamily: 'Inter, sans-serif', fontSize: 14, resize: 'vertical', display: 'block' },
  drawerDanger: { marginTop: 14, paddingTop: 14, borderTop: '1px solid #E5E7EB' },
  drawerLinkBtn: { display: 'block', padding: '10px 14px', borderRadius: 10, border: '1px solid #E5E7EB', background: '#F9FAFB', color: '#111827', fontWeight: 800, fontSize: 13, textDecoration: 'none', cursor: 'pointer' },
  toast: {
    position: 'fixed',
    left: '50%',
    bottom: 18,
    transform: 'translateX(-50%)',
    background: '#111827',
    color: '#fff',
    padding: '10px 14px',
    borderRadius: 999,
    fontWeight: 900,
    fontSize: 13,
    boxShadow: '0 10px 30px rgba(0,0,0,0.25)',
    zIndex: 2000,
  },
  chip: { display: 'inline-block', padding: '4px 10px', borderRadius: 999, border: '1px solid #E5E7EB', background: '#fff', fontWeight: 900, fontSize: 12, color: '#374151' },
  chipMore: { display: 'inline-block', padding: '4px 10px', borderRadius: 999, border: '1px solid #E5E7EB', background: '#F9FAFB', fontWeight: 900, fontSize: 12, color: '#6B7280' },
  smallDot: { opacity: 0.7 },
  readinessPill: { display: 'inline-flex', alignItems: 'center', padding: '4px 10px', borderRadius: 999, fontWeight: 900, fontSize: 12, border: '1px solid #E5E7EB' },
  readinessOk: { background: '#ecfdf5', borderColor: '#a7f3d0', color: '#065f46' },
  readinessWarn: { background: '#fff7ed', borderColor: '#fed7aa', color: '#9a3412' },
  helpDot: { marginLeft: 8, display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: 16, height: 16, borderRadius: 999, border: '1px solid #E5E7EB', background: '#fff', color: '#6B7280', fontSize: 11, fontWeight: 900, cursor: 'help' },

  searchInput: {
    padding: '8px 12px',
    border: '1px solid #d1d5db',
    borderRadius: 6,
    fontSize: 14,
    minWidth: 200,
  },
  select: {
    padding: '8px 12px',
    border: '1px solid #d1d5db',
    borderRadius: 6,
    fontSize: 14,
  },

  list: { listStyle: 'none', padding: 0, margin: 0 },
  listItem: {
    borderTop: '1px solid #eee',
    padding: '16px',
    transition: 'background-color 0.15s',
    cursor: 'pointer',
  },
  jobInfo: {},
  jobLink: {
    textDecoration: 'none',
    fontSize: 16,
    fontWeight: 600,
    color: '#2563eb',
    display: 'block',
    marginBottom: 6,
  },
  jobMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  jobDescription: {
    margin: 0,
    fontSize: 14,
    color: '#6b7280',
    lineHeight: 1.5,
  },
  userRow: {
    borderTop: '1px solid #eee',
    padding: '16px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    transition: 'background-color 0.15s',
  },
  smallText: { fontSize: 13, opacity: 0.7, marginTop: 4 },

  debugBox: {
    border: '1px dashed #999',
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
    fontSize: 13,
    backgroundColor: '#fffbeb',
  },
};
