/**
 * Shared styles for TradieDashboard.
 * Extracted to reduce maintainability debt in TradieDashboard.js.
 */
export const tradieDashboardStyles = {
  /** Full-bleed solid fill below header; inner `dashboardContainer` stays max-width centered. */
  dashboardShell: {
    width: '100%',
    minHeight: 'calc(100vh - 64px)',
    backgroundColor: '#F9FAFB',
    isolation: 'isolate',
  },
  dashboardContainer: {
    fontFamily: 'Inter, sans-serif',
    padding: '32px 24px',
    maxWidth: '1400px',
    margin: '0 auto',
  },
  /** Expert Tasks page: slightly tighter horizontal rhythm (work surface) */
  tasksPageContainer: {
    fontFamily: 'Inter, sans-serif',
    padding: '24px 20px 40px',
    maxWidth: '1400px',
    margin: '0 auto',
  },
  centered: {
    textAlign: 'center',
    padding: '100px 20px',
    fontSize: '16px',
    color: '#444',
  },
  welcomeSection: { marginBottom: '28px' },
  greeting: {
    fontFamily: 'Poppins, sans-serif',
    fontSize: '24px',
    fontWeight: '600',
    color: '#222',
    marginBottom: '4px',
  },
  subGreeting: { fontSize: '14px', color: '#757575', fontWeight: '400' },
  quoteEligibilityBanner: {
    display: 'flex',
    alignItems: 'center',
    gap: 14,
    padding: '14px 16px',
    borderRadius: 12,
    border: '1px solid #FF9100',
    backgroundColor: '#fff7ed',
    marginBottom: 18,
  },
  quoteEligibilityTitle: { fontFamily: 'Poppins, sans-serif', fontSize: 16, fontWeight: 700, color: '#222' },
  quoteEligibilityText: { fontSize: 13, color: '#444', marginTop: 2 },
  quoteEligibilityButton: {
    backgroundColor: '#FF9100',
    color: '#fff',
    border: 'none',
    borderRadius: 10,
    padding: '10px 14px',
    fontWeight: 900,
    cursor: 'pointer',
    fontSize: 13,
    whiteSpace: 'nowrap',
  },
  quoteEligibilityButtonSecondary: {
    backgroundColor: '#fff',
    color: '#FF9100',
    border: '1px solid #FF9100',
    borderRadius: 10,
    padding: '10px 14px',
    fontWeight: 900,
    cursor: 'pointer',
    fontSize: 13,
    whiteSpace: 'nowrap',
  },
  pendingDeletionBanner: {
    display: 'flex',
    alignItems: 'center',
    gap: 14,
    padding: '14px 16px',
    borderRadius: 12,
    border: '1px solid #FDBA74',
    backgroundColor: '#fff7ed',
    marginBottom: 18,
  },
  pendingDeletionCancelBtn: {
    backgroundColor: '#DC3545',
    color: '#fff',
    border: 'none',
    borderRadius: 10,
    padding: '10px 14px',
    fontWeight: 900,
    cursor: 'pointer',
    fontSize: 13,
    whiteSpace: 'nowrap',
  },
  modalOverlay: {
    position: 'fixed',
    inset: 0,
    backgroundColor: 'rgba(0,0,0,0.35)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    zIndex: 1000,
  },
  modalCard: {
    width: 'min(560px, 100%)',
    background: '#fff',
    borderRadius: 14,
    border: '1px solid #E0E0E0',
    boxShadow: '0 12px 30px rgba(0,0,0,0.18)',
    padding: 16,
  },
  modalHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 10 },
  modalClose: {
    background: 'transparent',
    border: 'none',
    fontSize: 22,
    lineHeight: 1,
    cursor: 'pointer',
    color: '#444',
    padding: '6px 10px',
    borderRadius: 10,
  },
  checkRow: { display: 'flex', gap: 10, alignItems: 'flex-start', padding: 10, border: '1px solid #eee', borderRadius: 12, background: '#fafafa' },
  checkDot: { width: 22, height: 22, borderRadius: 999, display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 900, fontSize: 12, marginTop: 1 },
  checkDotDone: { background: '#ecfdf5', border: '1px solid #a7f3d0', color: '#065f46' },
  checkDotTodo: { background: '#fffbeb', border: '1px solid #fde68a', color: '#92400e' },
  /** Wraps summary metrics on the dashboard so they read as secondary context. */
  statsSectionSecondary: {
    backgroundColor: '#F3F4F6',
    borderRadius: '12px',
    border: '1px solid #E5E7EB',
    padding: '16px',
    marginBottom: '24px',
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: '16px',
    marginBottom: 0,
  },
  statCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: '10px',
    padding: '16px 18px',
    textAlign: 'left',
    border: '1px solid #E5E7EB',
    boxShadow: 'none',
    transition: 'transform 0.2s, box-shadow 0.2s',
  },
  statValue: {
    fontFamily: 'Poppins, sans-serif',
    fontSize: '34px',
    fontWeight: '700',
    color: '#111827',
    marginBottom: '2px',
    lineHeight: 1.1,
  },
  statLabel: {
    fontSize: '11px',
    color: '#9CA3AF',
    fontWeight: '500',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    marginBottom: '10px',
  },
  statSubLabel: { fontSize: '14px', color: '#757575', fontWeight: '400' },
  /** Star row inside the Avg Rating card */
  statRatingRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    marginBottom: '4px',
  },
  statRatingStars: {
    display: 'inline-flex',
    gap: '1px',
    lineHeight: 1,
  },
  statRatingNumber: {
    fontFamily: 'Poppins, sans-serif',
    fontSize: '22px',
    fontWeight: '700',
    color: '#111827',
    lineHeight: 1,
  },
  statRatingEmpty: {
    fontSize: '15px',
    fontWeight: 500,
    color: '#9CA3AF',
    lineHeight: 1.3,
    marginBottom: '4px',
  },
  statRatingEmptyHint: {
    fontSize: '12px',
    color: '#B0B8C1',
    lineHeight: 1.4,
  },
  /** Reviews & ratings page (/tradie/reviews) */
  reviewsPageShell: {
    width: '100%',
    minHeight: 'calc(100vh - 64px)',
    backgroundColor: '#F9FAFB',
  },
  reviewsPageContainer: {
    fontFamily: 'Inter, sans-serif',
    padding: '32px 24px 56px',
    maxWidth: '900px',
    margin: '0 auto',
  },
  reviewsPageHeaderSection: {
    marginBottom: '28px',
    borderBottom: '1px solid #E5E7EB',
    paddingBottom: '20px',
  },
  reviewsPageHeading: {
    fontFamily: 'Poppins, sans-serif',
    fontSize: '26px',
    fontWeight: '700',
    color: '#111827',
    margin: '0 0 6px 0',
  },
  reviewsPageSubtitle: {
    fontSize: '14px',
    color: '#6B7280',
    margin: 0,
    lineHeight: 1.5,
  },
  /** Hero summary card */
  reviewsHeroCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: '14px',
    border: '1px solid #E5E7EB',
    borderLeft: '4px solid #14C5C5',
    boxShadow: '0 1px 4px rgba(0,0,0,0.06)',
    padding: '24px 28px',
    marginBottom: '20px',
    display: 'flex',
    alignItems: 'center',
    gap: '28px',
    flexWrap: 'wrap',
  },
  reviewsHeroAvgNumber: {
    fontFamily: 'Poppins, sans-serif',
    fontSize: '52px',
    fontWeight: '800',
    color: '#111827',
    lineHeight: 1,
    letterSpacing: '-0.02em',
    flexShrink: 0,
  },
  reviewsHeroRight: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  reviewsHeroStarRow: {
    display: 'inline-flex',
    gap: '2px',
    lineHeight: 1,
    marginBottom: '2px',
  },
  reviewsHeroLabel: {
    fontSize: '14px',
    color: '#6B7280',
    fontWeight: '400',
  },
  reviewsHeroEmptyText: {
    fontFamily: 'Poppins, sans-serif',
    fontSize: '17px',
    fontWeight: 600,
    color: '#9CA3AF',
    margin: 0,
  },
  reviewsHeroEmptyHint: {
    fontSize: '14px',
    color: '#B0B8C1',
    lineHeight: 1.5,
    margin: '6px 0 0 0',
    maxWidth: 380,
  },
  /** Metric chips row */
  reviewsMetaRow: {
    display: 'flex',
    gap: '12px',
    flexWrap: 'wrap',
    marginBottom: '32px',
  },
  reviewsMetaChip: {
    backgroundColor: '#FFFFFF',
    border: '1px solid #E5E7EB',
    borderRadius: '10px',
    padding: '12px 16px',
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
    minWidth: '110px',
    boxShadow: '0 1px 2px rgba(0,0,0,0.04)',
  },
  reviewsMetaChipLabel: {
    fontSize: '11px',
    fontWeight: 600,
    color: '#9CA3AF',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
  },
  reviewsMetaChipValue: {
    fontFamily: 'Poppins, sans-serif',
    fontSize: '20px',
    fontWeight: '700',
    color: '#111827',
    lineHeight: 1.1,
  },
  /** "Client reviews" list section */
  reviewsListSection: {
    marginTop: '0',
  },
  reviewsListHeader: {
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: '12px',
    marginBottom: '16px',
  },
  reviewsListTitle: {
    fontFamily: 'Poppins, sans-serif',
    fontSize: '18px',
    fontWeight: '700',
    color: '#111827',
    margin: 0,
  },
  reviewsListCount: {
    fontSize: '13px',
    color: '#6B7280',
    backgroundColor: '#F3F4F6',
    padding: '4px 10px',
    borderRadius: '12px',
    fontWeight: 500,
  },
  reviewsPageCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: '12px',
    border: '1px solid #E5E7EB',
    boxShadow: '0 1px 3px rgba(0,0,0,0.06)',
    padding: '20px 22px',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  reviewsPageCardTopRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
    flexWrap: 'wrap',
  },
  reviewsPageCardStars: {
    display: 'inline-flex',
    gap: '2px',
    lineHeight: 1,
  },
  reviewsPageCardDate: {
    fontSize: '12px',
    color: '#9CA3AF',
    fontWeight: 500,
    whiteSpace: 'nowrap',
  },
  reviewsPageCardText: {
    fontSize: '14px',
    color: '#374151',
    lineHeight: 1.65,
    margin: 0,
  },
  reviewsPageCardEmptyText: {
    fontSize: '14px',
    color: '#9CA3AF',
    fontStyle: 'italic',
    margin: 0,
  },
  reviewsVerifiedBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    fontSize: '11px',
    fontWeight: 600,
    color: '#0F766E',
    backgroundColor: '#F0FDFA',
    border: '1px solid #99F6E4',
    borderRadius: '6px',
    padding: '3px 8px',
    letterSpacing: '0.01em',
    alignSelf: 'flex-start',
  },
  reviewsPageEmptyState: {
    backgroundColor: '#FFFFFF',
    border: '1px solid #E5E7EB',
    borderRadius: '14px',
    padding: '48px 32px',
    textAlign: 'center',
  },
  reviewsPageEmptyTitle: {
    fontFamily: 'Poppins, sans-serif',
    fontSize: '18px',
    fontWeight: '600',
    color: '#374151',
    margin: '0 0 10px 0',
  },
  reviewsPageEmptyText: {
    fontSize: '14px',
    color: '#6B7280',
    lineHeight: 1.65,
    maxWidth: '420px',
    margin: '0 auto',
  },
  stripeTrustBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 16px',
    borderRadius: '20px',
    backgroundColor: '#F0FFF4',
    border: '1px solid #52d68a',
    color: '#1e7e34',
    fontSize: '12px',
    fontWeight: '600',
    marginBottom: '16px',
  },
  stripeBanner: {
    display: 'flex',
    alignItems: 'center',
    gap: 16,
    padding: '16px 20px',
    borderRadius: 12,
    border: '1px solid #60A5FA',
    backgroundColor: '#EFF6FF',
    marginBottom: 24,
    position: 'relative',
  },
  stripeBannerTitle: {
    fontFamily: 'Poppins, sans-serif',
    fontSize: 16,
    fontWeight: 600,
    color: '#222222',
    marginBottom: 4,
  },
  stripeBannerText: { fontSize: 14, color: '#444', lineHeight: '1.5', fontWeight: '400' },
  stripeButton: {
    fontFamily: 'Inter, sans-serif',
    backgroundColor: '#14C5C5',
    color: '#FFFFFF',
    border: 'none',
    borderRadius: '8px',
    padding: '10px 18px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    transition: 'transform 0.2s, box-shadow 0.2s, outline 0.2s',
    outline: 'none',
  },
  stripeButtonSecondary: {
    fontFamily: 'Inter, sans-serif',
    backgroundColor: 'transparent',
    color: '#14C5C5',
    border: '1px solid #14C5C5',
    borderRadius: '8px',
    padding: '10px 18px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    transition: 'transform 0.2s, outline 0.2s',
    outline: 'none',
  },
  dismissButton: {
    backgroundColor: 'transparent',
    border: 'none',
    color: '#757575',
    fontSize: 24,
    cursor: 'pointer',
    padding: '0 8px',
    lineHeight: '1',
    transition: 'color 0.2s',
    fontWeight: '400',
  },
  filterSection: { marginBottom: '24px' },
  needsAttentionPanel: {
    backgroundColor: '#FFFFFF',
    borderRadius: '12px',
    border: '1px solid #E0E0E0',
    boxShadow: '0 2px 8px rgba(0,0,0,0.06)',
    padding: '24px',
    marginBottom: '40px',
    borderLeft: '4px solid #14C5C5',
  },
  needsAttentionPanelHeader: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: '16px',
    marginBottom: '8px',
  },
  needsAttentionEyebrow: {
    fontSize: '11px',
    fontWeight: 700,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: '#14C5C5',
    marginBottom: '6px',
  },
  needsAttentionTitle: {
    fontFamily: 'Poppins, sans-serif',
    fontSize: '22px',
    fontWeight: 700,
    color: '#111827',
    margin: 0,
    lineHeight: 1.25,
  },
  needsAttentionHelper: {
    fontSize: '14px',
    color: '#6B7280',
    lineHeight: 1.5,
    margin: '10px 0 0 0',
    maxWidth: '640px',
  },
  needsAttentionCountLine: {
    fontSize: '13px',
    color: '#4B5563',
    fontWeight: 600,
    margin: '10px 0 0 0',
    lineHeight: 1.45,
  },
  needsAttentionOverflowRow: {
    marginBottom: '12px',
  },
  needsAttentionMoreLink: {
    fontFamily: 'Inter, sans-serif',
    fontSize: '14px',
    fontWeight: 600,
    color: '#0F766E',
    background: 'none',
    border: 'none',
    padding: 0,
    cursor: 'pointer',
    textDecoration: 'underline',
    textUnderlineOffset: '3px',
  },
  viewAllTasksButton: {
    fontFamily: 'Inter, sans-serif',
    fontSize: '14px',
    fontWeight: 600,
    color: '#0F766E',
    backgroundColor: '#FFFFFF',
    border: '1px solid #14C5C5',
    borderRadius: '10px',
    padding: '10px 18px',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    transition: 'background-color 0.2s, border-color 0.2s',
  },
  sectionHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '16px',
  },
  sectionTitle: {
    fontFamily: 'Poppins, sans-serif',
    fontSize: '24px',
    fontWeight: '600',
    color: '#222222',
    margin: 0,
  },
  sectionCount: {
    fontSize: '14px',
    color: '#757575',
    backgroundColor: '#F7F9FA',
    padding: '6px 12px',
    borderRadius: '16px',
    fontWeight: '500',
  },
  filterPills: { display: 'flex', gap: '12px', flexWrap: 'wrap' },
  filterPill: {
    padding: '10px 18px',
    borderRadius: '24px',
    border: '1px solid #E0E0E0',
    backgroundColor: '#FFFFFF',
    color: '#444',
    fontSize: '14px',
    fontWeight: '500',
    cursor: 'pointer',
    transition: 'all 0.2s, outline 0.2s',
    fontFamily: 'Inter, sans-serif',
    outline: 'none',
  },
  filterPillActive: {
    backgroundColor: '#14C5C5',
    color: '#FFFFFF',
    borderColor: '#14C5C5',
    fontWeight: '600',
  },
  emptyState: {
    textAlign: 'center',
    padding: '60px 20px',
    backgroundColor: '#FFFFFF',
    borderRadius: '12px',
    border: '1px solid #E0E0E0',
  },
  emptyTitle: {
    fontFamily: 'Poppins, sans-serif',
    fontSize: '18px',
    fontWeight: '600',
    color: '#222222',
    marginBottom: '12px',
  },
  emptyText: {
    fontSize: '14px',
    color: '#444',
    lineHeight: '1.6',
    maxWidth: '500px',
    margin: '0 auto',
  },
  jobList: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(min(100%, 350px), 1fr))',
    gap: '16px',
    marginBottom: 0,
  },
  jobCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: '12px',
    padding: '24px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.08)',
    border: '1px solid #E0E0E0',
    cursor: 'pointer',
    transition: 'transform 0.2s ease, box-shadow 0.2s ease, border-color 0.2s, outline 0.2s',
    outline: 'none',
    position: 'relative',
  },
  jobCardTopRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '16px',
    gap: '12px',
    flexWrap: 'wrap',
  },
  jobCardTitleRow: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: '10px',
    marginBottom: '12px',
  },
  unreadActivityDot: {
    width: 10,
    height: 10,
    borderRadius: 999,
    backgroundColor: '#14C5C5',
    marginTop: 6,
    flexShrink: 0,
    boxShadow: '0 0 0 2px rgba(20, 197, 197, 0.25)',
  },
  jobCardCriticalRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '12px',
    marginBottom: '12px',
    flexWrap: 'wrap',
  },
  budgetBadge: {
    padding: '6px 12px',
    borderRadius: '6px',
    fontSize: '14px',
    fontWeight: '700',
    backgroundColor: '#FEF3C7',
    color: '#92400E',
    border: '1px solid #FDE68A',
    whiteSpace: 'nowrap',
  },
  budgetMuted: {
    fontSize: '13px',
    fontWeight: 500,
    color: '#9CA3AF',
    whiteSpace: 'nowrap',
  },
  competitionBadge: {
    fontSize: '12px',
    color: '#6B7280',
    backgroundColor: '#F3F4F6',
    padding: '4px 10px',
    borderRadius: '4px',
    marginBottom: '12px',
    fontWeight: '500',
    display: 'inline-block',
  },
  jobQuoteHint: {
    fontSize: '12px',
    color: '#9CA3AF',
    marginBottom: '8px',
    fontWeight: 500,
  },
  jobTitle: {
    fontFamily: 'Poppins, sans-serif',
    fontSize: '18px',
    color: '#111827',
    margin: 0,
    fontWeight: 600,
    lineHeight: 1.35,
    flex: 1,
    minWidth: 0,
  },
  jobMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '13px',
    color: '#6B7280',
    flexWrap: 'wrap',
    marginBottom: '8px',
  },
  jobMetaItem: {},
  jobMetaDivider: { color: '#BDBDBD' },
  jobStatus: {
    padding: '5px 10px',
    borderRadius: '999px',
    fontSize: '12px',
    fontWeight: '600',
    textTransform: 'none',
    whiteSpace: 'nowrap',
    flexShrink: 0,
  },
  jobDescription: {
    fontSize: '14px',
    color: '#4B5563',
    lineHeight: 1.55,
    margin: '0 0 16px 0',
  },
  tagsRow: { display: 'flex', gap: '8px', flexWrap: 'wrap', marginBottom: '16px' },
  contextualBadge: {
    display: 'inline-block',
    padding: '6px 12px',
    borderRadius: '12px',
    fontSize: '12px',
    fontWeight: '600',
    border: '1px solid',
  },
  ctaButton: {
    width: '100%',
    padding: '12px 20px',
    backgroundColor: '#14C5C5',
    color: '#FFFFFF',
    border: 'none',
    borderRadius: '8px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'background-color 0.2s, transform 0.2s, outline 0.2s',
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    outline: 'none',
  },
  reviewsSection: { marginTop: '40px' },
  reviewGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
    gap: '16px',
  },
  reviewCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: '12px',
    padding: '20px',
    border: '1px solid #E0E0E0',
    boxShadow: '0 1px 3px rgba(0,0,0,0.08)',
  },
  reviewHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '12px',
  },
  ratingStars: { fontSize: '16px' },
  reviewDate: { fontSize: '12px', color: '#757575' },
  reviewText: { fontSize: '14px', color: '#444', lineHeight: '1.6', margin: 0 },
  reviewTextEmpty: { fontSize: '14px', color: '#757575', fontStyle: 'italic', margin: 0 },
  /** Expert Tasks page: full workspace shell (distinct from dashboard) */
  tasksWorkspaceIntro: {
    marginBottom: '12px',
  },
  tasksIntroInner: {
    width: '100%',
    maxWidth: '100%',
  },
  tasksHeadingRow: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: '8px 12px',
    marginBottom: '6px',
  },
  tasksBackLink: {
    fontSize: '13px',
    fontWeight: 500,
    color: '#6B7280',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontFamily: 'Inter, sans-serif',
    padding: '4px 0',
    margin: 0,
    textDecoration: 'underline',
    textUnderlineOffset: '3px',
    flexShrink: 0,
    alignSelf: 'center',
  },
  tasksControlsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: '12px',
    border: '1px solid #E5E7EB',
    boxShadow: '0 1px 2px rgba(0,0,0,0.04)',
    padding: '14px 16px',
    marginBottom: '20px',
  },
  tasksControlsPrimaryRow: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'stretch',
    gap: '10px',
  },
  tasksSearchInput: {
    flex: '1 1 220px',
    minWidth: 0,
    padding: '11px 14px',
    borderRadius: '10px',
    border: '1px solid #D1D5DB',
    fontSize: '15px',
    fontFamily: 'Inter, sans-serif',
    outline: 'none',
    backgroundColor: '#FAFAFA',
  },
  tasksSortSelect: {
    padding: '11px 14px',
    borderRadius: '10px',
    border: '1px solid #D1D5DB',
    fontSize: '14px',
    fontFamily: 'Inter, sans-serif',
    backgroundColor: '#FFFFFF',
    minWidth: 'min(100%, 200px)',
    flex: '0 1 200px',
    cursor: 'pointer',
    fontWeight: 500,
    color: '#374151',
  },
  tasksFilterDivider: {
    border: 'none',
    borderTop: '1px solid #EEF2F7',
    margin: '14px 0 12px 0',
  },
  tasksFilterRow: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '10px 12px',
  },
  tasksFilterLabel: {
    fontSize: '12px',
    fontWeight: 600,
    color: '#6B7280',
    letterSpacing: '0.02em',
    textTransform: 'uppercase',
    marginRight: 4,
    flexShrink: 0,
  },
  tasksListSection: {
    marginBottom: '8px',
  },
  tasksListSectionHeader: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: '8px 16px',
    marginBottom: '14px',
  },
  tasksListSectionTitle: {
    fontFamily: 'Poppins, sans-serif',
    fontSize: '18px',
    fontWeight: 600,
    color: '#111827',
    margin: 0,
  },
  /** Legacy toolbar — kept for any imports; prefer tasksControlsCard on Tasks page */
  tasksToolbar: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '12px',
    alignItems: 'center',
    marginBottom: '20px',
  },
  dashboardSectionLink: {
    fontSize: '14px',
    fontWeight: 700,
    color: '#14C5C5',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontFamily: 'Inter, sans-serif',
    padding: '4px 0',
  },
  /** Workspace job cards: denser, work-surface feel */
  jobCardWorkspace: {
    backgroundColor: '#FFFFFF',
    borderRadius: '10px',
    padding: '16px 18px',
    boxShadow: '0 1px 2px rgba(0,0,0,0.06)',
    border: '1px solid #E5E7EB',
    cursor: 'pointer',
    transition: 'transform 0.2s ease, box-shadow 0.2s ease, border-color 0.2s, outline 0.2s',
    outline: 'none',
    position: 'relative',
  },
  jobTitleWorkspace: {
    fontFamily: 'Poppins, sans-serif',
    fontSize: '17px',
    color: '#111827',
    margin: 0,
    fontWeight: 600,
    lineHeight: 1.35,
    flex: 1,
    minWidth: 0,
  },
  jobDescriptionWorkspace: {
    fontSize: '13px',
    color: '#4B5563',
    lineHeight: 1.5,
    margin: '0 0 12px 0',
  },
  ctaButtonWorkspace: {
    width: '100%',
    padding: '11px 16px',
    backgroundColor: '#14C5C5',
    color: '#FFFFFF',
    border: 'none',
    borderRadius: '8px',
    fontSize: '14px',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'background-color 0.2s, transform 0.2s, outline 0.2s',
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center',
    outline: 'none',
  },
  jobMetaWorkspace: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '12px',
    color: '#6B7280',
    flexWrap: 'wrap',
    marginBottom: '6px',
  },
  jobStatusWorkspace: {
    padding: '5px 11px',
    borderRadius: '999px',
    fontSize: '12px',
    fontWeight: 700,
    textTransform: 'none',
    whiteSpace: 'nowrap',
    flexShrink: 0,
  },
  jobCardTitleRowWorkspace: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: '10px',
    marginBottom: '10px',
  },
  jobCardCriticalRowWorkspace: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '12px',
    marginBottom: '8px',
    flexWrap: 'wrap',
  },
  unreadActivityDotWorkspace: {
    width: 9,
    height: 9,
    borderRadius: 999,
    backgroundColor: '#14C5C5',
    marginTop: 5,
    flexShrink: 0,
    boxShadow: '0 0 0 2px rgba(20, 197, 197, 0.22)',
  },
  budgetMutedWorkspace: {
    fontSize: '12px',
    fontWeight: 500,
    color: '#9CA3AF',
    whiteSpace: 'nowrap',
  },
};
