import { tradieDangerStyles } from './tradieAccountDangerStyles';

/** Page shell + banners + modal styles for Tradie Account Settings (matches ProfilePage tokens). */
export const tradieAccountSettingsPageStyles = {
  page: { background: '#F7F9FA', minHeight: 'calc(100vh - 64px)' },
  container: { maxWidth: 1100, margin: '0 auto', padding: '28px 32px 40px' },
  pageHeader: { marginBottom: 28 },
  pageTitle: { fontFamily: 'Poppins, sans-serif', fontSize: 28, fontWeight: 700, color: '#222', margin: 0, marginBottom: 8 },
  pageSubtitle: { fontSize: 15, color: '#666', margin: 0, lineHeight: 1.55, maxWidth: 640 },
  successBanner: {
    background: '#ecfdf5',
    border: '1px solid #a7f3d0',
    color: '#065f46',
    padding: '14px 18px',
    borderRadius: 12,
    fontSize: 14,
    marginBottom: 20,
    fontWeight: 600,
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  successIcon: { fontSize: 18, fontWeight: 900 },
  errorBanner: {
    background: '#fff1f2',
    border: '1px solid #fecdd3',
    color: '#9f1239',
    padding: '14px 18px',
    borderRadius: 12,
    fontSize: 14,
    marginBottom: 20,
  },
  label: { fontSize: 12, fontWeight: 900, color: '#555', marginBottom: 7 },
  hint: { fontSize: 11, color: '#888', marginTop: 6, lineHeight: 1.4 },
  input: { width: '100%', boxSizing: 'border-box', borderRadius: 10, border: '1px solid #E0E0E0', padding: '11px 13px', fontSize: 14, fontFamily: 'Inter, sans-serif' },
  buttonSecondary: { background: '#f3f4f6', color: '#374151', border: '1px solid #d1d5db', borderRadius: 10, padding: '11px 18px', cursor: 'pointer', fontWeight: 900, fontSize: 14 },
  buttonDanger: { background: '#DC3545', color: '#fff', border: 'none', borderRadius: 10, padding: '11px 18px', fontWeight: 900, fontSize: 14 },
  modalOverlay: {
    position: 'fixed',
    inset: 0,
    backgroundColor: 'rgba(0,0,0,0.35)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    zIndex: 1000,
  },
  modalCard: {
    width: 'min(560px, 100%)',
    background: '#fff',
    borderRadius: 14,
    border: '1px solid #E0E0E0',
    boxShadow: '0 12px 30px rgba(0,0,0,0.18)',
    padding: 16,
  },
  modalHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 10 },
  modalClose: { background: 'transparent', border: 'none', fontSize: 22, lineHeight: 1, cursor: 'pointer', color: '#444', padding: '6px 10px', borderRadius: 10 },
  ...tradieDangerStyles,
};
