/** Styles for tradie account danger zone (shared by ProfilePage history & TradieAccountSettingsPage). */
export const tradieDangerStyles = {
  dangerCard: { background: '#FFF9F9', border: '1px solid #F3D4D4', borderRadius: 16, padding: 24, marginBottom: 24 },
  dangerHeader: { display: 'flex', alignItems: 'flex-start', gap: 12, marginBottom: 20 },
  dangerIcon: { fontSize: 18, color: '#DC2626', flexShrink: 0, opacity: 0.55 },
  dangerTitle: { fontFamily: 'Inter, sans-serif', fontSize: 16, fontWeight: 600, color: '#7F1D1D', marginBottom: 8 },
  dangerSubtitleBold: { fontSize: 13, fontWeight: 700, color: '#991B1B', marginBottom: 4 },
  dangerSubtitle: { fontSize: 13, color: '#7F1D1D', lineHeight: 1.6, opacity: 0.72 },
  dangerActions: { display: 'flex', gap: 12, flexWrap: 'wrap', marginTop: 16 },
  deactivateButton: {
    background: '#FFFFFF',
    color: '#B91C1C',
    border: '1px solid #F0B7B7',
    borderRadius: 10,
    padding: '10px 18px',
    cursor: 'pointer',
    fontWeight: 600,
    fontSize: 13,
    fontFamily: 'Inter, sans-serif',
    transition: 'all 0.2s',
  },
  deleteButton: {
    background: '#FEE2E2',
    color: '#991B1B',
    border: '1px solid #FECACA',
    borderRadius: 10,
    padding: '10px 18px',
    cursor: 'pointer',
    fontWeight: 600,
    fontSize: 13,
    fontFamily: 'Inter, sans-serif',
    transition: 'all 0.2s',
  },
  cancelDeleteButton: {
    background: '#f3f4f6',
    color: '#374151',
    border: '1px solid #d1d5db',
    borderRadius: 10,
    padding: '10px 18px',
    cursor: 'pointer',
    fontWeight: 600,
    fontSize: 13,
    fontFamily: 'Inter, sans-serif',
    transition: 'all 0.2s',
  },
};
