'use strict';

/**
 * Central tuning for marketplace risk scoring, escalation, and monitoring eligibility.
 * Adjust weights/thresholds here — business logic reads this module only.
 */

const FACTOR_CODES = {
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  REFUND_FAILED: 'REFUND_FAILED',
  DISPUTE_STALE_24H: 'DISPUTE_STALE_24H',
  PAYMENT_FAILED_STALE_6H: 'PAYMENT_FAILED_STALE_6H',
  MULTIPLE_FLAGGED_MESSAGES: 'MULTIPLE_FLAGGED_MESSAGES',
  OFF_PLATFORM_CONTACT_ATTEMPT: 'OFF_PLATFORM_CONTACT_ATTEMPT',
  OFF_PLATFORM_PAYMENT_ATTEMPT: 'OFF_PLATFORM_PAYMENT_ATTEMPT',
  ABN_MISMATCH: 'ABN_MISMATCH',
  PROFILE_CHANGE_TRUST_IMPACTING: 'PROFILE_CHANGE_TRUST_IMPACTING',
  EXPERT_STRIPE_INCOMPLETE: 'EXPERT_STRIPE_INCOMPLETE',
  SUPPORT_ESCALATED: 'SUPPORT_ESCALATED',
  MULTIPLE_RECENT_CANCELLATIONS: 'MULTIPLE_RECENT_CANCELLATIONS',
  RAPID_ACCOUNT_CHANGES: 'RAPID_ACCOUNT_CHANGES',
  EXCESSIVE_ADMIN_TOUCHES: 'EXCESSIVE_ADMIN_TOUCHES',
  HIGH_RISK_KEYWORDS_IN_CHAT: 'HIGH_RISK_KEYWORDS_IN_CHAT',
  LEGAL_NAME_CHANGED_AFTER_VERIFICATION: 'LEGAL_NAME_CHANGED_AFTER_VERIFICATION',
  ABN_CHANGED: 'ABN_CHANGED',
  ABN_NAME_MISMATCH: 'ABN_NAME_MISMATCH',
  BUSINESS_DETAILS_INCONSISTENT: 'BUSINESS_DETAILS_INCONSISTENT',
  DISPUTE_OPEN: 'DISPUTE_OPEN',
  PROFILE_VERIFICATION_GAP: 'PROFILE_VERIFICATION_GAP',
  EXPERT_TRUST_REVIEW: 'EXPERT_TRUST_REVIEW',
  REPEAT_SUPPORT_TICKETS: 'REPEAT_SUPPORT_TICKETS',
};

/** Weight applied once per factor instance (deterministic cap in scorer). */
const FACTOR_WEIGHTS = {
  [FACTOR_CODES.PAYMENT_FAILED]: 32,
  [FACTOR_CODES.REFUND_FAILED]: 40,
  [FACTOR_CODES.DISPUTE_STALE_24H]: 36,
  [FACTOR_CODES.PAYMENT_FAILED_STALE_6H]: 24,
  [FACTOR_CODES.DISPUTE_OPEN]: 14,
  [FACTOR_CODES.MULTIPLE_FLAGGED_MESSAGES]: 18,
  [FACTOR_CODES.OFF_PLATFORM_CONTACT_ATTEMPT]: 20,
  [FACTOR_CODES.OFF_PLATFORM_PAYMENT_ATTEMPT]: 28,
  [FACTOR_CODES.ABN_MISMATCH]: 22,
  [FACTOR_CODES.PROFILE_CHANGE_TRUST_IMPACTING]: 16,
  [FACTOR_CODES.EXPERT_STRIPE_INCOMPLETE]: 14,
  [FACTOR_CODES.SUPPORT_ESCALATED]: 12,
  [FACTOR_CODES.MULTIPLE_RECENT_CANCELLATIONS]: 20,
  [FACTOR_CODES.RAPID_ACCOUNT_CHANGES]: 16,
  [FACTOR_CODES.EXCESSIVE_ADMIN_TOUCHES]: 12,
  [FACTOR_CODES.HIGH_RISK_KEYWORDS_IN_CHAT]: 22,
  [FACTOR_CODES.LEGAL_NAME_CHANGED_AFTER_VERIFICATION]: 26,
  [FACTOR_CODES.ABN_CHANGED]: 24,
  [FACTOR_CODES.ABN_NAME_MISMATCH]: 28,
  [FACTOR_CODES.BUSINESS_DETAILS_INCONSISTENT]: 18,
  [FACTOR_CODES.PROFILE_VERIFICATION_GAP]: 14,
  [FACTOR_CODES.EXPERT_TRUST_REVIEW]: 16,
  [FACTOR_CODES.REPEAT_SUPPORT_TICKETS]: 18,
};

const SCORE_CAP = 100;

const LEVEL_THRESHOLDS = [
  { level: 'low', min: 0, max: 24 },
  { level: 'medium', min: 25, max: 49 },
  { level: 'high', min: 50, max: 74 },
  { level: 'critical', min: 75, max: 100 },
];

/** Minimum score to consider for monitoring queue (in addition to existing requiresAdminAttention). */
const MONITORING_SCORE_MIN = 50;

/** Chat message: minimum aggregated severity before incrementing job risk from message signals (anti-flood). */
const MESSAGE_SIGNAL_SCORE_THRESHOLD = 8;

/** Max high-severity off-platform signals per evaluation window before escalating (placeholder for future time windows). */
const OFF_PLATFORM_REPEAT_THRESHOLD = 3;

/** Support: same user, hours window, ticket count to escalate. */
const SUPPORT_REPEAT_HOURS = 72;
const SUPPORT_REPEAT_COUNT = 3;

/** Payment failed age (hours) before ops escalation suggestion. */
const PAYMENT_FAILED_STALE_HOURS = 6;

/** Admin touches on job in 7d considered “excessive”. */
const ADMIN_TOUCH_COUNT_THRESHOLD = 8;

module.exports = {
  FACTOR_CODES,
  FACTOR_WEIGHTS,
  SCORE_CAP,
  LEVEL_THRESHOLDS,
  MONITORING_SCORE_MIN,
  MESSAGE_SIGNAL_SCORE_THRESHOLD,
  OFF_PLATFORM_REPEAT_THRESHOLD,
  SUPPORT_REPEAT_HOURS,
  SUPPORT_REPEAT_COUNT,
  PAYMENT_FAILED_STALE_HOURS,
  ADMIN_TOUCH_COUNT_THRESHOLD,
};
