export const LOCAL_SIGNUP_EMAIL_GUIDANCE = 'Local test mode: email delivery is simulated. Use the verification link generated by the Firebase Auth emulator.';

export const LOCAL_PROFILE_EMAIL_GUIDANCE = 'Local test mode: verification emails are not delivered to your inbox. Use the verification link generated by the Auth emulator.';

export const EMAIL_VERIFICATION_SENT = 'Verification email sent. Please check your inbox.';

const EMAIL_VERIFICATION_TOO_MANY = 'Too many attempts. Please wait a moment and try again.';
const EMAIL_VERIFICATION_UNAVAILABLE = "We couldn't send the verification email right now. Please try again.";
const EMAIL_VERIFICATION_GENERIC = "We couldn't send the verification email. Please try again.";

const SERVICE_ERROR_CODES = new Set([
  'auth/network-request-failed',
  'auth/internal-error',
  'auth/unavailable',
]);

// Applicant-safe copy for Firebase Auth email verification. Never returns provider text.
export function emailVerificationResendMessage(error) {
  const code = String(error?.code || '');
  if (code === 'auth/too-many-requests') return EMAIL_VERIFICATION_TOO_MANY;
  if (SERVICE_ERROR_CODES.has(code)) return EMAIL_VERIFICATION_UNAVAILABLE;
  return EMAIL_VERIFICATION_GENERIC;
}
